### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by khawar-islam** [deeplearning-wisc/dream-ood#9]
Hello @linyueqian @d12306 

Thank you for your work. In your code, your environment name is `conda activate dreamood` but it should be  `conda activate ldm`. If you check the first line of your `environment.yaml` file. As, I am installing Xformer, it gives an error and I already tried all versions still the error is consistent. If you can help me, I am following same steps you have mentioned

[Installed version] `pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu121`

`python3 scripts/dream_ood.py --plms --n_iter 50 --n_samples 3 --outdir output --loaded_embedding /media/cvpr/CM_24/dream-ood/outlier_npos_embed.npy --ckpt /media/cvpr/CM_24/dream-ood/sd-v1-4.ckpt --id_data in100 --skip_grid`

```
Traceback (most recent call last):
  File "scripts/dream_ood.py", line 534, in <module>
    main()
  File "scripts/dream_ood.py", line 479, in main
    samples_ddim, _ = sampler.sample(S=opt.ddim_steps,
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/cvpr/CM_24/dream-ood/ldm/models/diffusion/plms.py", line 97, in sample
    samples, intermediates = self.plms_sampling(conditioning, size,
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/cvpr/CM_24/dream-ood/ldm/models/diffusion/plms.py", line 152, in plms_sampling
    outs = self.p_sample_plms(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/cvpr/CM_24/dream-ood/ldm/models/diffusion/plms.py", line 219, in p_sample_plms
    e_t = get_model_output(x, t)
  File "/media/cvpr/CM_24/dream-ood/ldm/models/diffusion/plms.py", line 185, in get_model_output
    e_t_uncond, e_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "/media/cvpr/CM_24/dream-ood/ldm/models/diffusion/ddpm.py", line 987, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cvpr/CM_24/dream-ood/ldm/models/diffusion/ddpm.py", line 1410, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cvpr/CM_24/dream-ood/ldm/modules/diffusionmodules/openaimodel.py", line 732, in forward
    h = module(h, emb, context)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cvpr/CM_24/dream-ood/ldm/modules/diffusionmodules/openaimodel.py", line 85, in forward
    x = layer(x, context)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cvpr/CM_24/dream-ood/ldm/modules/attention.py", line 409, in forward
    x = block(x, context=context)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cvpr/CM_24/dream-ood/ldm/modules/attention.py", line 251, in forward
    hidden_states = self.attn1(self.norm1(hidden_states)) + hidden_states
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/cvpr/anaconda3/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/cvpr/CM_24/dream-ood/ldm/modules/attention.py", line 327, in forward
    self._maybe_init(q)
  File "/media/cvpr/CM_24/dream-ood/ldm/modules/attention.py", line 293, in _maybe_init
    self.attention_op = xformers.ops.AttentionOpDispatch(
TypeError: __init__() got an unexpected keyword argument 'dtype'
```

**Comment by khawar-islam** [comment]
Dear @d12306 Whenever you have a time, please have a look on my issue. I have tried several versions but didn't work for me

**Comment by khawar-islam** [comment]
@d12306 @linyueqian Please have a look on my issue and let me know the correct version

**Comment by d12306** [comment]
@khawar-islam please check here https://github.com/deeplearning-wisc/dream-ood/issues/7,

**Comment by d12306** [comment]
please feel free to try different versions, since it is related to your cuda, and torch versions, etc.
